<?php
	$mouseovereffect="onMouseOver=\"prevfontcolor=this.style.color;prevbgcolor=this.style.backgroundColor; this.style.backgroundColor=overbgcolor;this.style.color=overfontcolor\" onMouseOut=\"this.style.backgroundColor=prevbgcolor;this.style.color=prevfontcolor;\"";
	//STYLE OF TABLES
	$styleheader="font-size:10px;font-weight:bold;border-left:1px solid black;border-bottom:1px solid black;text-align:center;";
	$styledetails="font-size:10px;border-left:1px solid black;border-bottom:1px solid black;";
?>